### PR TITLE
resolve spk hld install-manifest-pipeline bug

### LINKED ISSUE #1055: Error on install-manifest-pipeline, HLD repo or manifest url not defined
**Describe the bug:**
`spk hld install-manifest-pipeline` throws error even when the HLD repo url and manifest url are defined in `spk-config.yaml`

**To Reproduce:**
- Populate the `azure_devops` section of the `spk-config.yaml`.
- Run `spk init -f spk-config.yaml`
- Run `spk hld install-manifest-pipeline`

**Expected behavior:**
It installs the pipeline.

Seen:
```
error:   Error occurred installing pipeline for HLD to Manifest pipeline
error:   HLD repo url or manifest url not defined.
```

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**

### PR DESCRIPTION
**Pull request by yradsmikham**
Close https://github.com/microsoft/bedrock/issues/1055.

### CODE REVIEW

**Review by bnookala — APPROVED** [review]

File: src/commands/hld/pipeline.ts [hunk 1]
```diff
@@ -74,6 +66,15 @@ export const populateValues = (opts: ICommandOptions) => {
 
   opts.buildScriptUrl = opts.buildScriptUrl || BUILD_SCRIPT_URL;
 
+  if (!opts.hldUrl || !opts.manifestUrl) {
```
Comment (andrebriggs) [inline src/commands/hld/pipeline.ts]: @yradsmikham this entire code block is contained. We don't reuse any of the const variables. Can we just encapsulate the entire block in a function?

As I look at the rest of the `populateValues` function there is refactoring that we can do outside of this PR

Comment (yradsmikham) [reply src/commands/hld/pipeline.ts]: Sure, will do.

**Review by samiyaakhtar — APPROVED** [review]

**Review by edaena — APPROVED** [review]

**Review by dennisseah — APPROVED** [review]
👍
