### PR TITLE
Patching for infra scaffold caching, PAT handling and macOS

### LINKED ISSUE #892: [SPK] Infra caching of tf template repo causes conflict with PATs
**Describe the bug:**

When using a PAT token for a private repo with infra, a temporary folder is created for that remote folder with the associated PATs. If the PATs expire or are revoked, the tempory folder spk maintains continues to override the previous PATs with use of spk infra commands.

**To Reproduce:**
- Create private repo with PATs
- Run an `spk infra scaffold` using private repo
- Revoke the PATs in AzDO
- Run an `spk infra scaffold` again using the private repo

**Expected behavior:**
The latest PATs will be used over the previous PATs

**Screenshots:**
```
naterose@naterose-Blade:~/Desktop/Microsoft/fy20/nate_fork/spk/tests$ $SPK_LOCATION infra scaffold -n discovery-infra-hld --source https://infra_account:$newPAT@naros32.visualstudio.com/ --version v0.0.1 --template template
.
.
.

info:    Checking if source repo: https://naros32.visualstudio.com/ has been already cloned to: /home/naterose/.spk/templates/_spk_testing__git_discovery_tf_template.
fatal: Authentication failed for 'https://infra_account:$old_PAT@naros32.visualstudio.com/
error:   There was an error checking the remote source repository: Error: fatal: Authentication failed for 'https://infra_account:$OLD_PATa@naros32.visualstudio.com/
```

**Does this require updates to documentation?:**
Yes

### PR DESCRIPTION
**Pull request by NathanielRose**
This PR closes [#892](https://github.com/microsoft/bedrock/issues/892), [#893](https://github.com/microsoft/bedrock/issues/893), [#932](https://github.com/microsoft/bedrock/issues/932).

- Introduces git clone caching retry logic that fixes conflicting history in cache repo and conflicting PAT tokens for cache directory
- Fixes running locally infra-validations for macOS users
- Fixes infra-validations script failing if `infra-generation-pipeline.yml` is not local to infra script

**What to check to approve**
- macOS users should run the `infra-validations.sh` locally
- Delete repo and recreate with same name and run scaffold. spk will now release cached directory for new remote cloning
- On a private repo, regenerate PAT tokens and run scaffold. spk will now release cached directory with outdated PAT in source URL

**Successful Builds**
- Infra validations in [naros32](https://naros32.visualstudio.com/spk-testing/_build/results?buildId=344&view=logs&j=8fe65ec1-57b5-590c-8e73-b2e70046a92a&t=5273a394-895a-588d-3853-b9fce385fa20) 
- Smoke Tests in epicstuff - pending approval modifying `spk-vg-testing` variable group

**Additional Thoughts**
- Retry logic may decrease code coverage, curious what are thoughts to build unit testing around scenarios that involve deletion of repos or outdated PATs
- Used @dennisseah 's approach for macOS support and sed. Was hoping to build natively in $SHELL. may revisit.

### CODE REVIEW

**Comment by NathanielRose** [comment]
It seems that `"$ACCESS_TOKEN_SECRET"` has been removed from both variable groups yet a [manual triggered build](https://dev.azure.com/epicstuff/bedrock/_build/results?buildId=10969&view=results) has ran successfully.

File: src/commands/infra/generate.ts [hunk 1]
```diff
@@ -244,22 +243,51 @@ export const validateRemoteSource = async (
   logger.info(
     `Checking if source repo: ${safeLoggingUrl} has been already cloned to: ${sourcePath}.`
   );
-
   try {
-    // Check if .git folder exists in ${sourcePath}, if not, then clone
-    // if already cloned, 'git pull'
-    if (fs.existsSync(path.join(sourcePath, ".git"))) {
-      await gitFetchPull(sourcePath, safeLoggingUrl);
```
Comment (dennisseah) [inline src/commands/infra/generate.ts:252]: [change request] Can you please remove `gitFetchPull` function from this file and also its unit tests.

File: src/commands/infra/generate.ts [hunk 2]
```diff
@@ -244,22 +243,51 @@ export const validateRemoteSource = async (
...
-    } else {
-      await gitClone(source, sourcePath);
```
Comment (dennisseah) [inline src/commands/infra/generate.ts:254]: [change request] Can you please remove `gitClone` function from this file and also its unit tests.

File: src/commands/infra/generate.ts [hunk 3]
```diff
@@ -244,22 +243,51 @@ export const validateRemoteSource = async (
...
-    }
+    // Clone remote source
+    await infraCommon.repoClone(sourcePath, source);
```
Comment (dennisseah) [inline src/commands/infra/generate.ts]: we have await `infraCommon` and await `gitCheckout` function calls in this `validateRemoteSource` function hence it may take more than 5 secs to execute this command on a slow network. Then this issue, https://github.com/microsoft/bedrock/issues/935 will resurface. One way to get around this is to mock `infraCommon.repoClone`. thanks

File: src/commands/infra/generate.ts [hunk 4]
```diff
@@ -244,22 +243,51 @@ export const validateRemoteSource = async (
...
     // Checkout tagged version
     logger.info(`Checking out template version: ${version}`);
     await gitCheckout(sourcePath, version);
   } catch (err) {
-    logger.error(err);
-    // TOFIX: this error should be rethrown
-    // and if we do, infra-validations.sh will fail
+    if (err instanceof Error) {
```
Comment (dennisseah) [inline src/commands/infra/generate.ts:260]: I suggest that we have small function for all the error handling code. Maybe break them down to 2 small functions (one for each case). So that they can be tested. Otherwise, code coverage is going to drop

**Review by dennisseah — CHANGES_REQUESTED** [review]

File: src/commands/infra/generate.ts (hunk 1 above)
Comment (yradsmikham) [reply src/commands/infra/generate.ts:252]: By concatenating the git commands in a single function again (i.e. `repoClone`), will we reduce code coverage?

Comment (NathanielRose) [reply src/commands/infra/generate.ts:252]: Keeping code in Dennis's format with decoupled git functions

File: src/commands/infra/generate.ts (hunk 3 above)
Comment (NathanielRose) [reply src/commands/infra/generate.ts]: Removed function

File: tests/infra-validations.sh [hunk 5]
```diff
@@ -35,13 +35,23 @@ infra_region=west/
...
 
+if [[ "$OSTYPE" == "darwin"* ]]; then
+  if ! [ -x "$(command -v gsed)" ]; then
+    echo 'Error: gnu-sed is not installed.' >&2
+    exit 1
+  fi
+  alias sed='gsed'
+  echo 'macOS detected'
+fi
+
```
Comment (yradsmikham) [inline tests/infra-validations.sh:54]: I'm not so sure if this logic is working because I am still encountering the following error:

```
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

@dennisseah, can you confirm?

**Review by yradsmikham — CHANGES_REQUESTED** [review]

File: tests/infra-validations.sh (hunk 5 above)
Comment (dennisseah) [reply tests/infra-validations.sh:54]: It works for me

**Review by dennisseah — APPROVED** [review]

**Review by andrebriggs — APPROVED** [review]
Looks good. @NathanielRose  Please run the integration tests manually after merge and build to ensure this works.

**Review by yradsmikham — APPROVED** [review]
