### PR TITLE
resolve bug with gitPull between repo tags and repo branches

### LINKED ISSUE #1303: SPK infra cache being modified during scaffold and failing
**Describe the bug:**
New moifications to `spk infra` command now conflict with retry logic and are modifying the cached remote source repo.

When checking the remote source after a `spk infra scaffold`, files have been changed causing the scaffold command to fail due to an unhandled retry case scenario.

**To Reproduce:**

Run the following commands:

1. `./spk-linux infra scaffold -n fabrikam/ --source https://github.com/microsoft/bedrock.git --version "nate.infra.relative.paths" --template cluster/environments/azure-simple`
2. `./spk-linux infra scaffold -n fabrikam/west --source https://github.com/microsoft/bedrock.git --version "nate.infra.relative.paths" --template cluster/environments/azure-simple`
3. An error will be thrown: See Error 1
4. Navigate to cache remote folders: `cd ~/.spk/templates`
5. `git status`
6. Modifications have been changed similar to error 2:

**Expected behavior:**
SPK will retry if there have been changes to the source template by deleting the folder and recloning.

**Screenshots:**
[spk.log](https://github.com/microsoft/bedrock/files/4419205/spk.log)

### Error 1

```
naterose@naterose-Blade:~/Desktop/Microsoft/fy20/nate_fork/spk/dist$ ./spk-linux infra scaffold -n fabrikam/east --source https://github.com/microsoft/bedrock.git --version "nate.infra.relative.paths" --template cluster/environments/azure-simple
error:   Env variable needs to be defined for test_name
info:    Unable to load SPK configuration file; run `spk init` to initialize your global configuration or ensure you have passed all required parameters to the called function.
info:    The infrastructure repository containing the remote terraform template repo and access token was not specified in spk-config.yml. Checking passed arguments.
info:    All required options are configured via command line for scaffolding, expecting public remote repository for terraform templates or PAT embedded in source URL.
info:    Converted to: _microsoft_bedrock_git
info:    Checking if source: /home/naterose/.spk/templates/_microsoft_bedrock_git is stored locally.
info:    Source template folder found. Validating existence of repository.
info:    Remote source repo: https://github.com/microsoft/bedrock.git exists.
info:    Checking if source repo: https://github.com/microsoft/bedrock.git has been already cloned to: /home/naterose/.spk/templates/_microsoft_bedrock_git.
From https://github.com/microsoft/bedrock
 * branch            master     -> FETCH_HEAD

warn:    FAILURE DETECTED: Checking the error
error:   
code: 1000
message: infra-scaffold-cmd-failed: Infra scaffold command was not successfully executed.
  code: 1100
  message: infra-err-retry-validating-remote-git: Failure error thrown during retrying validating remote git source.
  details: From https://github.com/microsoft/bedrock
 * branch            master     -> FETCH_HEAD
```

### Error 2
```
naterose@naterose-Blade:~/.spk/templates/_microsoft_bedrock_git$ git status
On branch nate.infra.relative.paths
Your branch is up to date with 'origin/nate.infra.relative.paths'.

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:
	modified:   cluster/azure/acr/main.tf
	modified:   cluster/azure/aks/main.tf
	modified:   cluster/azure/keyvault/main.tf
	modified:   cluster/azure/provider/main.tf
	modified:   cluster/azure/subnet/main.tf
	modified:   cluster/azure/subnet/outputs.tf
	modified:   cluster/azure/subnet/variables.tf
	modified:   cluster/azure/vnet/main.tf
	modified:   cluster/azure/vnet/output.tf
	modified:   cluster/common/flux/deploy_flux.sh
	modified:   cluster/environments/azure-common-infra/main.tf
	modified:   cluster/environments/azure-common-infra/variables.tf
	modified:   cluster/environments/azure-common-infra/vnet.tf
	modified:   cluster/environments/azure-multiple-clusters-waf-tm-apimgmt/aks-centralus.tf
	modified:   cluster/environments/azure-multiple-clusters-waf-tm-apimgmt/aks-eastus.tf
	modified:   cluster/environments/azure-multiple-clusters-waf-tm-apimgmt/aks-westus.tf
	modified:   cluster/environments/azure-multiple-clusters/aks-centralus.tf
	modified:   cluster/environments/azure-multiple-clusters/aks-eastus.tf
	modified:   cluster/environments/azure-multiple-clusters/aks-westus.tf
	modified:   cluster/environments/azure-simple/main.tf
	modified:   cluster/environments/azure-single-keyvault-cosmos-mongo-db-simple/main.tf
	modified:   cluster/environments/azure-single-keyvault-cosmos-mongo-db-simple/variables.tf
	modified:   cluster/environments/azure-single-keyvault/main.tf
	modified:   cluster/environments/azure-single-keyvault/variables.tf
	modified:   docs/devops/README.md
	modified:   docs/firstWorkload/README.md
	modified:   docs/hld-to-manifest.md
	modified:   docs/multicluster.md
	modified:   gitops/azure-devops/build.sh
	new file:   security.md
	modified:   test/bedrock_Azure_common_kv_test.go
	modified:   test/bedrock_Azure_mc_test.go
	modified:   test/bedrock_Azure_single_cosmos_mongo_test.go
	modified:   tools/prereqs/common_funcs.sh
	modified:   tools/prereqs/setup_terraform.sh

Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both modified:   README.md
```

**Additional context:**
It could be possible that an error may have to deal with `git checkout` between branches?
**Does this require updates to documentation?:**
No

### PR DESCRIPTION
**Pull request by yradsmikham**
Close https://github.com/microsoft/bedrock/issues/1303.

### CODE REVIEW

File: src/commands/infra/generate.ts [hunk 1]
```diff
@@ -146,14 +147,22 @@ export const createGenerated = (projectPath: string): void => {
...
-  await simpleGit(sourcePath).pull("origin", "master");
-  logger.info(`${safeLoggingUrl} already cloned. Performing 'git pull'...`);
+  try {
+    await exec("git", ["symbolic-ref", "HEAD"], { cwd: sourcePath });
+    logger.info(
+      `${safeLoggingUrl} already cloned and a git branch is currently checked out. Performing 'git pull'...`
+    );
+    await simpleGit(sourcePath).pull();
+  } catch (err) {
+    logger.info(
```
Comment (dennisseah) [inline src/commands/infra/generate.ts:162]: question: what is the assumption here. Is it that exec or simpleGit functions fail and we ignore the error?

Comment (yradsmikham) [reply src/commands/infra/generate.ts:162]: The logic is that if the exec command fails, then the passed in version argument is a git tag as opposed to a git branch, in which case don't perform `git pull` because it will cause the error that is seen now.

**Review by samiyaakhtar — APPROVED** [review]

**Review by dennisseah — APPROVED** [review]

**Review by NathanielRose — APPROVED** [review]
