### PR TITLE
Fix test in serviceEndpoint

### LINKED ISSUE #1035: Incorrect test on addServiceEndpoint function in serviceEndpoint.ts
**Describe the bug:**
it is supposed to be a positive test, yet we are catching exception in test. and left a half of the method untested

**To Reproduce:**
yarn test.

**Expected behavior:**
Positive test = going thru all the path in the function and return expected result.

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**
No

### PR DESCRIPTION
**Pull request by dennisseah**
Closes https://github.com/microsoft/bedrock/issues/1035

also boost code coverage to 100%

### CODE REVIEW

File: src/lib/pipelines/serviceEndpoint.ts [hunk 1]
```diff
@@ -40,12 +40,9 @@ export const createServiceEndpointIfNotExists = async (
...
     }
 
-    if (serviceEndpoint === null || serviceEndpoint === undefined) {
-      throw new Error(
-        "Either unable to find a existing service endpoint by name or create a new service endpoint"
-      );
-    }
-
+    // addServiceEndpoint always return a value of type, IServiceEndpoint
+    // it will never eturn null or undefined.
```
Comment (edaena) [inline src/lib/pipelines/serviceEndpoint.ts]: typo: eturn -> return

**Review by edaena — APPROVED** [review]

**Review by sarath-p — APPROVED** [review]

File: src/lib/pipelines/serviceEndpoint.ts (hunk 1 above)
Comment (dennisseah) [reply src/lib/pipelines/serviceEndpoint.ts]: accept
