### PR TITLE
fix(671) - Fix error thrown when `spk init` has not been called

### LINKED ISSUE #671: [SPK] Bug: Error when calling help and no config file in SPK
When downloading SPK on a new environment and no config file I call

`$ spk-macos service -h` or `$ spk-macos service` 

The result is 
```
error:   An error occurred while loading configuration
 Error: ENOENT: no such file or directory, stat '/Users/andrebriggs/.spk/config.yaml'
fs.js:859
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat '/Users/andrebriggs/.spk/config.yaml'
    at Object.statSync (fs.js:859:3)
    at Object.fs.statSync (pkg/prelude/bootstrap.js:924:32)
    at Object.loadConfiguration (/snapshot/spk/dist/spk.js:0:0)
    at Object.executeCommand (/snapshot/spk/dist/spk.js:0:0)
    at Object.<anonymous> (/snapshot/spk/dist/spk.js:0:0)
    at i (/snapshot/spk/dist/spk.js:0:0)
    at /snapshot/spk/dist/spk.js:0:0
    at Object.<anonymous> (/snapshot/spk/dist/spk.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:768:10)
```

We shouldn't be expecting a config file when `help` is called

### PR DESCRIPTION
**Pull request by evanlouie**
- Added top level try/catch for `executeCommand`.
- `loadConfiguration()` is only called when attempting to retrieve the spk config via `Config()`
- Refactored to only have config be retrievable via the `Config()` function.
- Moved code related to spk-config to `config.ts`

fixes https://github.com/microsoft/bedrock/issues/671

### CODE REVIEW

File: src/commands/infra/validate.ts [hunk 1]
```diff
@@ -2,8 +2,8 @@ import child_process from "child_process";
 import commander from "commander";
```
Comment (samiyaakhtar) [inline src/commands/infra/validate.ts:2]: wooo vaildate -> validate

**Review by samiyaakhtar — APPROVED** [review]

**Review by edaena — APPROVED** [review]
