### PR TITLE
spk deployment create should link pr based deployment correctly

### LINKED ISSUE #925: Introspection scripts should link PR based pipelines correctly
**Describe the bug:** When a manifest generation pipeline is triggered based on an automated PR merge into the HLD, the commit identifier is different from the commit into the HLD that was being merged. The `spk deployment create` command needs to support taking in a PR identifier and differentiating a PR based build from a regular master commit into HLD. 

**To Reproduce:**
When a PR is made into the HLD and merged to cause manifest generation, there's a broken link in the deployment, such as below:
Screen Shot 2020-01-29 at 2 47 37 PM

**Expected behavior:**
The manifest generation pipeline should recognize the deployment it was automatically triggered from, such as below: 
Screen Shot 2020-01-29 at 2 49 02 PM

**Screenshots:**

**Additional context:**

**Does this require updates to documentation?:**

### PR DESCRIPTION
**Pull request by samiyaakhtar**
Closes https://github.com/microsoft/bedrock/issues/925

### CODE REVIEW

File: src/lib/azure/deploymenttable.ts [hunk 1]
```diff
@@ -135,82 +145,120 @@ export const updateACRToHLDPipeline = (
...
+    );
+  }
+};
 
-        const newEntry: any = {};
-        newEntry.PartitionKey = tableInfo.partitionKey;
-        newEntry.RowKey = getRowKey();
-        newEntry.p3 = pipelineId.toLowerCase();
-        newEntry.hldCommitId = hldCommitId.toLowerCase();
+export const updateHLDtoManifestHelper = (
```
Comment (edaena) [inline src/lib/azure/deploymenttable.ts:192]: Missing function documentation header

File: src/lib/azure/deploymenttable.ts [hunk 2]
```diff
@@ -135,82 +145,120 @@ export const updateACRToHLDPipeline = (
...
+    const entriesArray = await findMatchingDeployments(tableInfo, "pr", pr);
+    return updateHLDtoManifestHelper(
+      entriesArray,
+      tableInfo,
+      hldCommitId,
+      pipelineId,
+      manifestCommitId,
+      pr
+    );
+  } else {
```
Comment (edaena) [inline src/lib/azure/deploymenttable.ts]: nit: don't need the else

**Review by edaena — APPROVED** [review]

**Review by yradsmikham — APPROVED** [review]
