### PR TITLE
Use display name for creating service components and ingress routes

### LINKED ISSUE #898: ingress routes do not use display name
**Describe the bug:**

Ingressroutes being written improperly - not using displayName attribute in service object

**To Reproduce:**

bedrock.yaml: 
```
rings:
  master:
    isDefault: true
services:
  ./:
    displayName: fabrikam-frontend-service
    helm:
      chart:
        branch: master
        git: 'https://dev.azure.com/foo/bar/baz'
        path: chart
    middlewares:
      - ''
```

will produce:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: .-master
spec:
  routes:
    - kind: Rule
      match: 'PathPrefix(`/.`) && Headers(`Ring`, `master`)'
      services:
        - name: .-master
          port: 8000
```

where the name of the ingress route, the path prefix, and the service name are all wrong (using the path to the service, instead of the display name0

**Expected behavior:**

we should be outputting the correct service name, correct ingress route name using the ingress display name, and correct path prefix

**Screenshots:**

**Additional context:**

presently we're not using `displayName` at all

**Does this require updates to documentation?:**

no

Related to #810

### PR DESCRIPTION
**Pull request by bnookala**
Fixes https://github.com/microsoft/bedrock/issues/898

### CODE REVIEW

File: src/commands/hld/reconcile.ts [hunk 1]
```diff
@@ -151,15 +151,24 @@ export const reconcileHld = async (
...
   )) {
-    const pathBase = path.basename(serviceRelPath);
-    const serviceName = pathBase;
-    logger.info(`Reconciling service: ${pathBase}`);
+    const serviceName =
+      serviceConfig.displayName || path.basename(serviceRelPath);
+
+    // No name, cannot generate proper routes and middlewares
+    if (serviceName === "." || !serviceName) {
+      logger.warn(
```
Comment (evanlouie) [inline src/commands/hld/reconcile.ts:159]: might want to throw an error and exit instead

**Review by evanlouie — APPROVED** [review]
lgtm

File: src/commands/hld/reconcile.ts (hunk 1 above)
Comment (bnookala) [reply src/commands/hld/reconcile.ts:159]: might be a larger design choice as there's a few places where we simply just `continue` instead of failing fast - perhaps we can revisit this

**Review by mtarng — APPROVED** [review]
