### PR TITLE
Fix incorrect `fab set` call

### LINKED ISSUE #945: HLD update build step does not update the correct image tag
**Describe the bug:**

Committing a change to my application repository does _not_ update the proper component configuration in the HLD generated by reconcile

**To Reproduce:**

1. Set up any buildable application via spk, and create a HLD + HLD lifecycle pipeline
2. Commit to application repository on any ring branch
3. Observe that HLD update step does _not_ update HLD to reflect the container image built at the ring level in the HLD.

**Expected behavior:**
 
My HLD to have a Pull Request against it containing an image tag update against the proper subcomponent

**Additional context:**

https://github.com/CatalystCode/spk/blob/master/src/lib/fileutils.ts#L240 invokes `fab set` on $PROJECT_NAME_LOWER, which does not work as $PROJECT_NAME_LOWER does _not_ reflect the proper path of the chart within an HLD.

A correct invocation of `fab set` would be to update the helm component at the leaf node of the HLD ie:

`fab set --subcomponent "$REPOSITORY.$SERVICE_NAME.$RING.$CHART_NAME  image.tag=$(Build.SourceBranchName)-$(Build.BuildNumber)`

**Does this require updates to documentation?:**

Yes

### PR DESCRIPTION
**Pull request by evanlouie**
Calls to `fab set` in generated pipeline YAML files have been using the
incorrect component path to set -- only using the `<service-name>` instead of the
full path in the HLD of
`<repository/application-name>.<service-name>.<ring-name>.chart`. This fix
corrects the outputted `fab set` call.

- Corrected the `fab set` call in service build/update pipeline to `set` the
  correct component path.
- Corrected some incorrect error messaging in gitutils.

fixes https://github.com/microsoft/bedrock/issues/945

### CODE REVIEW

File: src/lib/fileutils.ts [hunk 1]
```diff
@@ -194,7 +194,7 @@ export const serviceBuildAndUpdatePipeline = (
                   ``,
                   `# Update HLD`,
                   `git checkout -b "$BRANCH_NAME"`,
-                  `../fab/fab set --subcomponent $SERVICE_NAME_LOWER image.tag=$(Build.SourceBranchName)-$(Build.BuildNumber)`,
+                  `../fab/fab set --subcomponent $(Build.Repository.Name).$SERVICE_NAME_LOWER.$(Build.SourceBranchName).chart image.tag=$(Build.SourceBranchName)-$(Build.BuildNumber)`,
```
Comment (bnookala) [inline src/lib/fileutils.ts]: we might need to do some massaging of sourceBranchName - what if it was a git flow branch name (ie fix/some-issue-number or dev/foo-bar-baz)

**Review by bnookala — CHANGES_REQUESTED** [review]

File: src/lib/fileutils.ts (hunk 1 above)
Comment (bnookala) [reply src/lib/fileutils.ts]: i think in that case we'd want something that transforms / to a - ie:

release/dev -> release-dev

File: src/test/mockFactory.ts [hunk 2]
```diff
@@ -122,7 +122,7 @@ export const createTestServiceBuildAndUpdatePipelineYaml = (
                   ``,
                   `# Update HLD`,
                   `git checkout -b "$BRANCH_NAME"`,
-                  `../fab/fab set --subcomponent $SERVICE_NAME_LOWER image.tag=$(Build.SourceBranchName)-$(Build.BuildNumber)`,
+                  `../fab/fab set --subcomponent $(Build.Repository.Name).$SERVICE_NAME_LOWER.$(Build.SourceBranchName).chart image.tag=$(Build.SourceBranchName)-$(Build.BuildNumber)`,
```
Comment (andrebriggs) [inline src/test/mockFactory.ts]: @evanlouie in the description you say 
> Calls to fab set in generated pipeline YAML files have been using the
incorrect component path to set -- only using the <service-name> instead of the
full path in the HLD of
<repository/application-name>-<service-name>-<ring-name>-chart. This fix
corrects the outputted fab set call.

However here we have `<application-name>-<service-name>-<ring-name> .chart` with a DOT chart. Is this correct?

**Review by andrebriggs — DISMISSED** [review]

File: src/test/mockFactory.ts (hunk 2 above)
Comment (evanlouie) [reply src/test/mockFactory.ts]: whoops. Wrote the comment incorrectly. We delimit the parts with `.` not `-`.
So `<application-name>.<service-name>.<ring-name>.chart` is correct

**Comment by mtarng** [comment]
Does this handle the case where service name contains `.`'s? ie. `fabrikam.acme.frontend`?

**Comment by evanlouie** [comment]
> Does this handle the case where service name contains `.`'s? ie. `fabrikam.acme.frontend`?

@mtarng we do a one off escaping for the `fab set` call to do define the service name as `FAB_SAFE_SERVICE_NAME=$(SERVICE_NAME_LOWER | tr . - | tr / -)`. The rest of the usage of service name in the build&update pipeline use SERVICE_NAME_LOWER

**Review by mtarng — APPROVED** [review]
This melts my brain. typescript -> bash -> azdo pipeline variables.

File: src/lib/fileutils.ts (hunk 1 above)
Comment (evanlouie) [reply src/lib/fileutils.ts]: it now uses a SAFE_SOURCE_BRANCH var that is `$(echo $(Build.SourceBranchName) | tr / - | tr . -)` (all `/` and `.` are replaced with `-`)

**Review by bnookala — APPROVED** [review]
